In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv('./diabetes_latih.csv')

df.head()


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            8      188             78              0        0  47.9   
1            7      152             88             44        0  50.0   
2            2       99             52             15       94  24.6   
3            1      109             56             21      135  25.2   
4            2       88             74             19       53  29.0   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.137   43        1  
1                     0.337   36        1  
2                     0.637   21        0  
3                     0.833   23        0  
4                     0.229   22        0

In [10]:
X_train = df.values
X_train = np.delete(X_train,8,axis=1)

y_train = df['Outcome'].values

df = pd.read_csv('./diabetes_uji.csv')

X_test = df.values
X_test = np.delete(X_test,8,axis=1)

y_test = df['Outcome'].values


print(X_train)

df.head()

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  4.    114.     65.    ...  21.9     0.432  37.   ]
 [  9.    156.     86.    ...  34.3     1.189  42.   ]
 [  1.    153.     82.    ...  40.6     0.687  23.   ]]


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [12]:
#Melakukan Normalisasi yaitu menggunakan MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

X_train = MinMaxScaler().fit_transform(X_train)
X_test = MinMaxScaler().fit_transform(X_test)


print(X_test)

[[0.4        0.75126904 0.59016393 ... 0.61090909 0.24602814 0.60416667]
 [0.06666667 0.43147208 0.54098361 ... 0.48363636 0.12074444 0.20833333]
 [0.53333333 0.92893401 0.52459016 ... 0.42363636 0.26645483 0.22916667]
 ...
 [0.26666667 0.5786802  0.53278689 ... 0.39818182 0.15751248 0.33333333]
 [0.6        0.79187817 0.70491803 ... 0.62363636 0.50113482 0.4375    ]
 [0.06666667 0.77664975 0.67213115 ... 0.73818182 0.27326373 0.04166667]]


In [13]:
print(X_train)

[[0.4        0.75126904 0.59016393 ... 0.61090909 0.24602814 0.60416667]
 [0.06666667 0.43147208 0.54098361 ... 0.48363636 0.12074444 0.20833333]
 [0.53333333 0.92893401 0.52459016 ... 0.42363636 0.26645483 0.22916667]
 ...
 [0.26666667 0.5786802  0.53278689 ... 0.39818182 0.15751248 0.33333333]
 [0.6        0.79187817 0.70491803 ... 0.62363636 0.50113482 0.4375    ]
 [0.06666667 0.77664975 0.67213115 ... 0.73818182 0.27326373 0.04166667]]


In [20]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(hidden_layer_sizes=3, learning_rate_init=0.1, max_iter=100)

clf.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=3, learning_rate_init=0.1, max_iter=100)

In [16]:
y_pred = clf.predict(X_test)

In [8]:
#mealkukan penilaian akurasi 
from sklearn.metrics import accuracy_score

round(accuracy_score(y_test,y_pred),3)

0.649

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154 entries, 0 to 153
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               154 non-null    int64  
 1   Glucose                   154 non-null    int64  
 2   BloodPressure             154 non-null    int64  
 3   SkinThickness             154 non-null    int64  
 4   Insulin                   154 non-null    int64  
 5   BMI                       154 non-null    float64
 6   DiabetesPedigreeFunction  154 non-null    float64
 7   Age                       154 non-null    int64  
 8   Outcome                   154 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 11.0 KB
